---
- name: print os facts from fact module
  hosts: all
  tasks:
    - name: print os name
      debug:
        var: ansible_distribution
          #this facts can be fetch from ansible -m setup all
          
    - name: Print free RAM memory
      debug:
        var: ansible_memory_mb.real.free

    - name: Print used RAM Memory
      debug:
        var: ansible_memory_mb.real.used

    - name: Processor information
      debug:
        var: ansible_processor


    


