---
# handlers file for post-install

- name: Chronyd restart
  service:
    name: chronyd
    state: restarted
    enabled: yes
  when: ansible_distribution == "AlmaLinux"

- name: Ntp restart
  service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu"

